name: STRONG
channels:
    - https://metachannel.conda-forge.org/bioconda,conda-forge/--max-build-no
dependencies:
    - snakemake >=5.5.4
    - python
    - biopython
    - bowtie2 
    - samtools
    - prodigal
    - spades
    - blast
    - concoct
    - mafft
    - trimal
    - fasttree
    - gfapy
    - future
