name: STRONG
channels:
    - https://metachannel.conda-forge.org/bioconda,anaconda,conda-forge/--max-build-no
    - bioconda
dependencies:
    - snakemake >=5.5.4
    - python
    - biopython
    - bowtie2 
    - samtools
    - prodigal
    - spades
    - blast
    - concoct
    - mafft
    - trimal
    - fasttree
    - gfapy
    - future
    - pysam
    - pygam
    - statsmodels
    - pathos
    - ete3

